// This file is auto-generated by @hey-api/openapi-ts

export type Event =
	| ({
			type: 'lsp.client.diagnostics';
	  } & EventLspClientDiagnostics)
	| ({
			type: 'permission.updated';
	  } & EventPermissionUpdated)
	| ({
			type: 'file.edited';
	  } & EventFileEdited)
	| ({
			type: 'installation.updated';
	  } & EventInstallationUpdated)
	| ({
			type: 'message.updated';
	  } & EventMessageUpdated)
	| ({
			type: 'message.removed';
	  } & EventMessageRemoved)
	| ({
			type: 'message.part.updated';
	  } & EventMessagePartUpdated)
	| ({
			type: 'storage.write';
	  } & EventStorageWrite)
	| ({
			type: 'session.updated';
	  } & EventSessionUpdated)
	| ({
			type: 'session.deleted';
	  } & EventSessionDeleted)
	| ({
			type: 'session.idle';
	  } & EventSessionIdle)
	| ({
			type: 'session.error';
	  } & EventSessionError)
	| ({
			type: 'file.watcher.updated';
	  } & EventFileWatcherUpdated);

export type EventLspClientDiagnostics = {
	type: string;
	properties: {
		serverID: string;
		path: string;
	};
};

export type EventPermissionUpdated = {
	type: string;
	properties: PermissionInfo;
};

export type PermissionInfo = {
	id: string;
	sessionID: string;
	title: string;
	metadata: {
		[key: string]: unknown;
	};
	time: {
		created: number;
	};
};

export type EventFileEdited = {
	type: string;
	properties: {
		file: string;
	};
};

export type EventInstallationUpdated = {
	type: string;
	properties: {
		version: string;
	};
};

export type EventMessageUpdated = {
	type: string;
	properties: {
		info: Message;
	};
};

export type Message =
	| ({
			role: 'user';
	  } & UserMessage)
	| ({
			role: 'assistant';
	  } & AssistantMessage);

export type UserMessage = {
	id: string;
	sessionID: string;
	role: string;
	parts: Array<UserMessagePart>;
	time: {
		created: number;
	};
};

export type UserMessagePart =
	| ({
			type: 'text';
	  } & TextPart)
	| ({
			type: 'file';
	  } & FilePart);

export type TextPart = {
	type: string;
	text: string;
	synthetic?: boolean;
};

export type FilePart = {
	type: string;
	mime: string;
	filename?: string;
	url: string;
};

export type AssistantMessage = {
	id: string;
	sessionID: string;
	role: string;
	parts: Array<AssistantMessagePart>;
	time: {
		created: number;
		completed?: number;
	};
	error?:
		| ({
				name: 'ProviderAuthError';
		  } & ProviderAuthError)
		| ({
				name: 'UnknownError';
		  } & UnknownError)
		| ({
				name: 'MessageOutputLengthError';
		  } & MessageOutputLengthError)
		| ({
				name: 'MessageAbortedError';
		  } & MessageAbortedError);
	system: Array<string>;
	modelID: string;
	providerID: string;
	path: {
		cwd: string;
		root: string;
	};
	summary?: boolean;
	cost: number;
	tokens: {
		input: number;
		output: number;
		reasoning: number;
		cache: {
			read: number;
			write: number;
		};
	};
};

export type AssistantMessagePart =
	| ({
			type: 'text';
	  } & TextPart)
	| ({
			type: 'tool';
	  } & ToolPart)
	| ({
			type: 'step-start';
	  } & StepStartPart)
	| ({
			type: 'step-finish';
	  } & StepFinishPart);

export type ToolPart = {
	type: string;
	id: string;
	tool: string;
	state: ToolState;
};

export type ToolState =
	| ({
			status: 'pending';
	  } & ToolStatePending)
	| ({
			status: 'running';
	  } & ToolStateRunning)
	| ({
			status: 'completed';
	  } & ToolStateCompleted)
	| ({
			status: 'error';
	  } & ToolStateError);

export type ToolStatePending = {
	status: string;
};

export type ToolStateRunning = {
	status: string;
	input?: unknown;
	title?: string;
	metadata?: {
		[key: string]: unknown;
	};
	time: {
		start: number;
	};
};

export type ToolStateCompleted = {
	status: string;
	input: {
		[key: string]: unknown;
	};
	output: string;
	title: string;
	metadata: {
		[key: string]: unknown;
	};
	time: {
		start: number;
		end: number;
	};
};

export type ToolStateError = {
	status: string;
	input: {
		[key: string]: unknown;
	};
	error: string;
	time: {
		start: number;
		end: number;
	};
};

export type StepStartPart = {
	type: string;
};

export type StepFinishPart = {
	type: string;
	cost: number;
	tokens: {
		input: number;
		output: number;
		reasoning: number;
		cache: {
			read: number;
			write: number;
		};
	};
};

export type ProviderAuthError = {
	name: string;
	data: {
		providerID: string;
		message: string;
	};
};

export type UnknownError = {
	name: string;
	data: {
		message: string;
	};
};

export type MessageOutputLengthError = {
	name: string;
	data: {
		[key: string]: unknown;
	};
};

export type MessageAbortedError = {
	name: string;
	data: {
		[key: string]: unknown;
	};
};

export type EventMessageRemoved = {
	type: string;
	properties: {
		sessionID: string;
		messageID: string;
	};
};

export type EventMessagePartUpdated = {
	type: string;
	properties: {
		part: AssistantMessagePart;
		sessionID: string;
		messageID: string;
	};
};

export type EventStorageWrite = {
	type: string;
	properties: {
		key: string;
		content?: unknown;
	};
};

export type EventSessionUpdated = {
	type: string;
	properties: {
		info: Session;
	};
};

export type Session = {
	id: string;
	parentID?: string;
	share?: {
		url: string;
	};
	title: string;
	version: string;
	time: {
		created: number;
		updated: number;
	};
	revert?: {
		messageID: string;
		part: number;
		snapshot?: string;
	};
};

export type EventSessionDeleted = {
	type: string;
	properties: {
		info: Session;
	};
};

export type EventSessionIdle = {
	type: string;
	properties: {
		sessionID: string;
	};
};

export type EventSessionError = {
	type: string;
	properties: {
		sessionID?: string;
		error?:
			| ({
					name: 'ProviderAuthError';
			  } & ProviderAuthError)
			| ({
					name: 'UnknownError';
			  } & UnknownError)
			| ({
					name: 'MessageOutputLengthError';
			  } & MessageOutputLengthError)
			| ({
					name: 'MessageAbortedError';
			  } & MessageAbortedError);
	};
};

export type EventFileWatcherUpdated = {
	type: string;
	properties: {
		file: string;
		event: string;
	};
};

export type App = {
	user: string;
	hostname: string;
	git: boolean;
	path: {
		config: string;
		data: string;
		root: string;
		cwd: string;
		state: string;
	};
	time: {
		initialized?: number;
	};
};

export type Config = {
	/**
	 * JSON schema reference for configuration validation
	 */
	$schema?: string;
	/**
	 * Theme name to use for the interface
	 */
	theme?: string;
	keybinds?: KeybindsConfig;
	/**
	 * Share newly created sessions automatically
	 */
	autoshare?: boolean;
	/**
	 * Automatically update to the latest version
	 */
	autoupdate?: boolean;
	/**
	 * Disable providers that are loaded automatically
	 */
	disabled_providers?: Array<string>;
	/**
	 * Model to use in the format of provider/model, eg anthropic/claude-2
	 */
	model?: string;
	mode?: {
		build?: ModeConfig;
		plan?: ModeConfig;
		[key: string]: ModeConfig | undefined;
	};
	log_level?: LogLevel;
	/**
	 * Custom provider configurations and model overrides
	 */
	provider?: {
		[key: string]: {
			api?: string;
			name?: string;
			env?: Array<string>;
			id?: string;
			npm?: string;
			models: {
				[key: string]: {
					id?: string;
					name?: string;
					release_date?: string;
					attachment?: boolean;
					reasoning?: boolean;
					temperature?: boolean;
					tool_call?: boolean;
					cost?: {
						input: number;
						output: number;
						cache_read?: number;
						cache_write?: number;
					};
					limit?: {
						context: number;
						output: number;
					};
					options?: {
						[key: string]: unknown;
					};
				};
			};
			options?: {
				[key: string]: unknown;
			};
		};
	};
	/**
	 * MCP (Model Context Protocol) server configurations
	 */
	mcp?: {
		[key: string]:
			| ({
					type: 'local';
			  } & McpLocalConfig)
			| ({
					type: 'remote';
			  } & McpRemoteConfig);
	};
	/**
	 * Additional instruction files or patterns to include
	 */
	instructions?: Array<string>;
	experimental?: {
		hook?: {
			file_edited?: {
				[key: string]: Array<{
					command: Array<string>;
					environment?: {
						[key: string]: string;
					};
				}>;
			};
			session_completed?: Array<{
				command: Array<string>;
				environment?: {
					[key: string]: string;
				};
			}>;
		};
	};
};

export type KeybindsConfig = {
	/**
	 * Leader key for keybind combinations
	 */
	leader: string;
	/**
	 * Show help dialog
	 */
	app_help: string;
	/**
	 * Switch mode
	 */
	switch_mode: string;
	/**
	 * Open external editor
	 */
	editor_open: string;
	/**
	 * Create a new session
	 */
	session_new: string;
	/**
	 * List all sessions
	 */
	session_list: string;
	/**
	 * Share current session
	 */
	session_share: string;
	/**
	 * Unshare current session
	 */
	session_unshare: string;
	/**
	 * Interrupt current session
	 */
	session_interrupt: string;
	/**
	 * Compact the session
	 */
	session_compact: string;
	/**
	 * Toggle tool details
	 */
	tool_details: string;
	/**
	 * List available models
	 */
	model_list: string;
	/**
	 * List available themes
	 */
	theme_list: string;
	/**
	 * List files
	 */
	file_list: string;
	/**
	 * Close file
	 */
	file_close: string;
	/**
	 * Search file
	 */
	file_search: string;
	/**
	 * Split/unified diff
	 */
	file_diff_toggle: string;
	/**
	 * Create/update AGENTS.md
	 */
	project_init: string;
	/**
	 * Clear input field
	 */
	input_clear: string;
	/**
	 * Paste from clipboard
	 */
	input_paste: string;
	/**
	 * Submit input
	 */
	input_submit: string;
	/**
	 * Insert newline in input
	 */
	input_newline: string;
	/**
	 * Scroll messages up by one page
	 */
	messages_page_up: string;
	/**
	 * Scroll messages down by one page
	 */
	messages_page_down: string;
	/**
	 * Scroll messages up by half page
	 */
	messages_half_page_up: string;
	/**
	 * Scroll messages down by half page
	 */
	messages_half_page_down: string;
	/**
	 * Navigate to previous message
	 */
	messages_previous: string;
	/**
	 * Navigate to next message
	 */
	messages_next: string;
	/**
	 * Navigate to first message
	 */
	messages_first: string;
	/**
	 * Navigate to last message
	 */
	messages_last: string;
	/**
	 * Toggle layout
	 */
	messages_layout_toggle: string;
	/**
	 * Copy message
	 */
	messages_copy: string;
	/**
	 * Revert message
	 */
	messages_revert: string;
	/**
	 * Exit the application
	 */
	app_exit: string;
};

export type ModeConfig = {
	model?: string;
	prompt?: string;
	tools?: {
		[key: string]: boolean;
	};
};

/**
 * Log level
 */
export type LogLevel = 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';

export type Provider = {
	api?: string;
	name: string;
	env: Array<string>;
	id: string;
	npm?: string;
	models: {
		[key: string]: Model;
	};
};

export type Model = {
	id: string;
	name: string;
	release_date: string;
	attachment: boolean;
	reasoning: boolean;
	temperature: boolean;
	tool_call: boolean;
	cost: {
		input: number;
		output: number;
		cache_read?: number;
		cache_write?: number;
	};
	limit: {
		context: number;
		output: number;
	};
	options: {
		[key: string]: unknown;
	};
};

export type McpLocalConfig = {
	/**
	 * Type of MCP server connection
	 */
	type: string;
	/**
	 * Command and arguments to run the MCP server
	 */
	command: Array<string>;
	/**
	 * Environment variables to set when running the MCP server
	 */
	environment?: {
		[key: string]: string;
	};
	/**
	 * Enable or disable the MCP server on startup
	 */
	enabled?: boolean;
};

export type McpRemoteConfig = {
	/**
	 * Type of MCP server connection
	 */
	type: string;
	/**
	 * URL of the remote MCP server
	 */
	url: string;
	/**
	 * Enable or disable the MCP server on startup
	 */
	enabled?: boolean;
};

export type _Error = {
	data: {
		[key: string]: unknown;
	};
};

export type Match = {
	path: {
		text: string;
	};
	lines: {
		text: string;
	};
	line_number: number;
	absolute_offset: number;
	submatches: Array<{
		match: {
			text: string;
		};
		start: number;
		end: number;
	}>;
};

export type Symbol = {
	name: string;
	kind: number;
	location: {
		uri: string;
		range: Range;
	};
};

export type Range = {
	start: {
		line: number;
		character: number;
	};
	end: {
		line: number;
		character: number;
	};
};

export type File = {
	path: string;
	added: number;
	removed: number;
	status: 'added' | 'deleted' | 'modified';
};

export type Mode = {
	name: string;
	model?: {
		modelID: string;
		providerID: string;
	};
	prompt?: string;
	tools: {
		[key: string]: boolean;
	};
};

export type GetEventData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/event';
};

export type GetEventResponses = {
	/**
	 * Event stream
	 */
	200: Event;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type GetAppData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/app';
};

export type GetAppResponses = {
	/**
	 * 200
	 */
	200: App;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type PostAppInitData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/app/init';
};

export type PostAppInitResponses = {
	/**
	 * Initialize the app
	 */
	200: boolean;
};

export type PostAppInitResponse =
	PostAppInitResponses[keyof PostAppInitResponses];

export type GetConfigData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/config';
};

export type GetConfigResponses = {
	/**
	 * Get config info
	 */
	200: Config;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type GetSessionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/session';
};

export type GetSessionResponses = {
	/**
	 * List of sessions
	 */
	200: Array<Session>;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type PostSessionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/session';
};

export type PostSessionErrors = {
	/**
	 * Bad request
	 */
	400: _Error;
};

export type PostSessionError = PostSessionErrors[keyof PostSessionErrors];

export type PostSessionResponses = {
	/**
	 * Successfully created session
	 */
	200: Session;
};

export type PostSessionResponse =
	PostSessionResponses[keyof PostSessionResponses];

export type DeleteSessionByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/session/{id}';
};

export type DeleteSessionByIdResponses = {
	/**
	 * Successfully deleted session
	 */
	200: boolean;
};

export type DeleteSessionByIdResponse =
	DeleteSessionByIdResponses[keyof DeleteSessionByIdResponses];

export type PostSessionByIdInitData = {
	body?: {
		providerID: string;
		modelID: string;
	};
	path: {
		/**
		 * Session ID
		 */
		id: string;
	};
	query?: never;
	url: '/session/{id}/init';
};

export type PostSessionByIdInitResponses = {
	/**
	 * 200
	 */
	200: boolean;
};

export type PostSessionByIdInitResponse =
	PostSessionByIdInitResponses[keyof PostSessionByIdInitResponses];

export type PostSessionByIdAbortData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/session/{id}/abort';
};

export type PostSessionByIdAbortResponses = {
	/**
	 * Aborted session
	 */
	200: boolean;
};

export type PostSessionByIdAbortResponse =
	PostSessionByIdAbortResponses[keyof PostSessionByIdAbortResponses];

export type DeleteSessionByIdShareData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/session/{id}/share';
};

export type DeleteSessionByIdShareResponses = {
	/**
	 * Successfully unshared session
	 */
	200: Session;
};

export type DeleteSessionByIdShareResponse =
	DeleteSessionByIdShareResponses[keyof DeleteSessionByIdShareResponses];

export type PostSessionByIdShareData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/session/{id}/share';
};

export type PostSessionByIdShareResponses = {
	/**
	 * Successfully shared session
	 */
	200: Session;
};

export type PostSessionByIdShareResponse =
	PostSessionByIdShareResponses[keyof PostSessionByIdShareResponses];

export type PostSessionByIdSummarizeData = {
	body?: {
		providerID: string;
		modelID: string;
	};
	path: {
		/**
		 * Session ID
		 */
		id: string;
	};
	query?: never;
	url: '/session/{id}/summarize';
};

export type PostSessionByIdSummarizeResponses = {
	/**
	 * Summarized session
	 */
	200: boolean;
};

export type PostSessionByIdSummarizeResponse =
	PostSessionByIdSummarizeResponses[keyof PostSessionByIdSummarizeResponses];

export type GetSessionByIdMessageData = {
	body?: never;
	path: {
		/**
		 * Session ID
		 */
		id: string;
	};
	query?: never;
	url: '/session/{id}/message';
};

export type GetSessionByIdMessageResponses = {
	/**
	 * List of messages
	 */
	200: Array<Message>;
};

export type GetSessionByIdMessageResponse =
	GetSessionByIdMessageResponses[keyof GetSessionByIdMessageResponses];

export type PostSessionByIdMessageData = {
	body?: {
		providerID: string;
		modelID: string;
		mode: string;
		parts: Array<UserMessagePart>;
	};
	path: {
		/**
		 * Session ID
		 */
		id: string;
	};
	query?: never;
	url: '/session/{id}/message';
};

export type PostSessionByIdMessageResponses = {
	/**
	 * Created message
	 */
	200: AssistantMessage;
};

export type PostSessionByIdMessageResponse =
	PostSessionByIdMessageResponses[keyof PostSessionByIdMessageResponses];

export type GetConfigProvidersData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/config/providers';
};

export type GetConfigProvidersResponses = {
	/**
	 * List of providers
	 */
	200: {
		providers: Array<Provider>;
		default: {
			[key: string]: string;
		};
	};
};

export type GetConfigProvidersResponse =
	GetConfigProvidersResponses[keyof GetConfigProvidersResponses];

export type GetFindData = {
	body?: never;
	path?: never;
	query: {
		pattern: string;
	};
	url: '/find';
};

export type GetFindResponses = {
	/**
	 * Matches
	 */
	200: Array<Match>;
};

export type GetFindResponse = GetFindResponses[keyof GetFindResponses];

export type GetFindFileData = {
	body?: never;
	path?: never;
	query: {
		query: string;
	};
	url: '/find/file';
};

export type GetFindFileResponses = {
	/**
	 * File paths
	 */
	200: Array<string>;
};

export type GetFindFileResponse =
	GetFindFileResponses[keyof GetFindFileResponses];

export type GetFindSymbolData = {
	body?: never;
	path?: never;
	query: {
		query: string;
	};
	url: '/find/symbol';
};

export type GetFindSymbolResponses = {
	/**
	 * Symbols
	 */
	200: Array<Symbol>;
};

export type GetFindSymbolResponse =
	GetFindSymbolResponses[keyof GetFindSymbolResponses];

export type GetFileData = {
	body?: never;
	path?: never;
	query: {
		path: string;
	};
	url: '/file';
};

export type GetFileResponses = {
	/**
	 * File content
	 */
	200: {
		type: 'raw' | 'patch';
		content: string;
	};
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type GetFileStatusData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/file/status';
};

export type GetFileStatusResponses = {
	/**
	 * File status
	 */
	200: Array<File>;
};

export type GetFileStatusResponse =
	GetFileStatusResponses[keyof GetFileStatusResponses];

export type PostLogData = {
	body?: {
		/**
		 * Service name for the log entry
		 */
		service: string;
		/**
		 * Log level
		 */
		level: 'debug' | 'info' | 'error' | 'warn';
		/**
		 * Log message
		 */
		message: string;
		/**
		 * Additional metadata for the log entry
		 */
		extra?: {
			[key: string]: unknown;
		};
	};
	path?: never;
	query?: never;
	url: '/log';
};

export type PostLogResponses = {
	/**
	 * Log entry written successfully
	 */
	200: boolean;
};

export type PostLogResponse = PostLogResponses[keyof PostLogResponses];

export type GetModeData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/mode';
};

export type GetModeResponses = {
	/**
	 * List of modes
	 */
	200: Array<Mode>;
};

export type GetModeResponse = GetModeResponses[keyof GetModeResponses];

export type ClientOptions = {
	baseUrl: 'http://localhost:4096' | (string & {});
};
